### ISSUE TITLE
[Request]: 复读机

### ISSUE THREAD

**Issue by 123Windows31** [daizihan233/HanBot#30]
### 请确定您做到了一下内容

- [X] 我确定这是一个有意义的Issue，且目前没有此功能。

### 新功能名称

复读机

### 新功能描述

@机器人 复读 指定内容 几次
让机器人复读指定内容几次
或
@机器人 开启复读模式
每发一条消息复读一次
然后呢
@机器人 关闭复读模式

**Comment by daizihan233** [comment]
建议检测到某一句话有多个人在重复就复读那句话（bushi）

**Comment by 123Windows31** [comment]
屑东西终于鸟我了

**Comment by daizihan233** [comment]
屑东西

**Comment by daizihan233** [comment]
话说是不是能用来刷屏（）

**Comment by daizihan233** [comment]
nnd，鸟我

**Comment by 123Windows31** [comment]
吱

**Comment by 123Windows31** [comment]
好像能刷屏

**Comment by 123Windows31** [comment]
就像是QX的复读（）

**Comment by 123Windows31** [comment]
自动+1（）

**Comment by daizihan233** [comment]
搞个自动+1罢，防止有的~~大傻逼~~滥用

**Comment by daizihan233** [comment]
建议检测到某一句话有多个人在重复就复读那句话（bushi） daizihan233 ***@***.*** 签名由 网易邮箱大师 定制 在2022年03月24日 21:09，123Windows31 写道： 请确定您做到了一下内容 我确定这是一个有意义的Issue，且目前没有此功能。 新功能名称 复读机 新功能描述 @机器人 复读 指定内容 让机器人复读指定内容 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were assigned.Message ID: ***@***.***>
